/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CanonRegistry__factory } from './CanonRegistry__factory';
export { MaskSBT__factory } from './MaskSBT__factory';
//# sourceMappingURL=index.js.map
