/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CanonRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "FEE_DENOMINATOR"
      | "FOUNDATION_FEE"
      | "IMPLEMENTER_FEE"
      | "RELAYER_ROLE"
      | "TREASURY_ROLE"
      | "anchor"
      | "anchorAttestation"
      | "anchorReceipt"
      | "anchorWarrant"
      | "balances"
      | "baseFee"
      | "emergencyWithdraw"
      | "foundationTreasury"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "implementerTreasury"
      | "isAnchored"
      | "lastAnchorBlock"
      | "pause"
      | "paused"
      | "renounceRole"
      | "revokeRole"
      | "setBaseFee"
      | "setTreasuries"
      | "supportsInterface"
      | "totalAnchors"
      | "totalFeesCollected"
      | "unpause"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Anchored"
      | "AttestationAnchored"
      | "Paused"
      | "ReceiptAnchored"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "WarrantAnchored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FOUNDATION_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IMPLEMENTER_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELAYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "anchor",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorAttestation",
    values: [BytesLike, BytesLike, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorReceipt",
    values: [BytesLike, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorWarrant",
    values: [BytesLike, BytesLike, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "baseFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "foundationTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "implementerTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAnchored",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastAnchorBlock",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuries",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAnchors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FOUNDATION_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IMPLEMENTER_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELAYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "anchor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "anchorAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorWarrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "foundationTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementerTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAnchored", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastAnchorBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBaseFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAnchors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AnchoredEvent {
  export type InputTuple = [
    warrantDigest: BytesLike,
    attestationDigest: BytesLike,
    relayer: AddressLike,
    subjectTag: BytesLike,
    controllerDidHash: BytesLike,
    assurance: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    warrantDigest: string,
    attestationDigest: string,
    relayer: string,
    subjectTag: string,
    controllerDidHash: string,
    assurance: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    warrantDigest: string;
    attestationDigest: string;
    relayer: string;
    subjectTag: string;
    controllerDidHash: string;
    assurance: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationAnchoredEvent {
  export type InputTuple = [
    attestationHash: BytesLike,
    warrantHash: BytesLike,
    enterpriseHash: BytesLike,
    enterpriseId: string,
    attestationId: string,
    submitter: AddressLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    attestationHash: string,
    warrantHash: string,
    enterpriseHash: string,
    enterpriseId: string,
    attestationId: string,
    submitter: string,
    ts: bigint
  ];
  export interface OutputObject {
    attestationHash: string;
    warrantHash: string;
    enterpriseHash: string;
    enterpriseId: string;
    attestationId: string;
    submitter: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptAnchoredEvent {
  export type InputTuple = [
    receiptHash: BytesLike,
    warrantHash: BytesLike,
    attestationHash: BytesLike,
    subjectWallet: AddressLike,
    submitter: AddressLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    receiptHash: string,
    warrantHash: string,
    attestationHash: string,
    subjectWallet: string,
    submitter: string,
    ts: bigint
  ];
  export interface OutputObject {
    receiptHash: string;
    warrantHash: string;
    attestationHash: string;
    subjectWallet: string;
    submitter: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WarrantAnchoredEvent {
  export type InputTuple = [
    warrantHash: BytesLike,
    subjectHandleHash: BytesLike,
    enterpriseHash: BytesLike,
    enterpriseId: string,
    warrantId: string,
    submitter: AddressLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    warrantHash: string,
    subjectHandleHash: string,
    enterpriseHash: string,
    enterpriseId: string,
    warrantId: string,
    submitter: string,
    ts: bigint
  ];
  export interface OutputObject {
    warrantHash: string;
    subjectHandleHash: string;
    enterpriseHash: string;
    enterpriseId: string;
    warrantId: string;
    submitter: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CanonRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CanonRegistry;
  waitForDeployment(): Promise<this>;

  interface: CanonRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  FOUNDATION_FEE: TypedContractMethod<[], [bigint], "view">;

  IMPLEMENTER_FEE: TypedContractMethod<[], [bigint], "view">;

  RELAYER_ROLE: TypedContractMethod<[], [string], "view">;

  TREASURY_ROLE: TypedContractMethod<[], [string], "view">;

  anchor: TypedContractMethod<
    [
      warrantDigest: BytesLike,
      attestationDigest: BytesLike,
      subjectTag: BytesLike,
      controllerDidHash: BytesLike,
      assurance: BigNumberish
    ],
    [void],
    "payable"
  >;

  anchorAttestation: TypedContractMethod<
    [
      attestationHash: BytesLike,
      warrantHash: BytesLike,
      enterpriseHash: BytesLike,
      enterpriseId: string,
      attestationId: string
    ],
    [void],
    "payable"
  >;

  anchorReceipt: TypedContractMethod<
    [
      receiptHash: BytesLike,
      warrantHash: BytesLike,
      attestationHash: BytesLike,
      subjectWallet: AddressLike
    ],
    [void],
    "payable"
  >;

  anchorWarrant: TypedContractMethod<
    [
      warrantHash: BytesLike,
      subjectHandleHash: BytesLike,
      enterpriseHash: BytesLike,
      enterpriseId: string,
      warrantId: string
    ],
    [void],
    "payable"
  >;

  balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  baseFee: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  foundationTreasury: TypedContractMethod<[], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  implementerTreasury: TypedContractMethod<[], [string], "view">;

  isAnchored: TypedContractMethod<[hash: BytesLike], [boolean], "view">;

  lastAnchorBlock: TypedContractMethod<[hash: BytesLike], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setBaseFee: TypedContractMethod<
    [_baseFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasuries: TypedContractMethod<
    [_foundationTreasury: AddressLike, _implementerTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalAnchors: TypedContractMethod<[], [bigint], "view">;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FOUNDATION_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IMPLEMENTER_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RELAYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TREASURY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "anchor"
  ): TypedContractMethod<
    [
      warrantDigest: BytesLike,
      attestationDigest: BytesLike,
      subjectTag: BytesLike,
      controllerDidHash: BytesLike,
      assurance: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "anchorAttestation"
  ): TypedContractMethod<
    [
      attestationHash: BytesLike,
      warrantHash: BytesLike,
      enterpriseHash: BytesLike,
      enterpriseId: string,
      attestationId: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "anchorReceipt"
  ): TypedContractMethod<
    [
      receiptHash: BytesLike,
      warrantHash: BytesLike,
      attestationHash: BytesLike,
      subjectWallet: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "anchorWarrant"
  ): TypedContractMethod<
    [
      warrantHash: BytesLike,
      subjectHandleHash: BytesLike,
      enterpriseHash: BytesLike,
      enterpriseId: string,
      warrantId: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "foundationTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "implementerTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isAnchored"
  ): TypedContractMethod<[hash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastAnchorBlock"
  ): TypedContractMethod<[hash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseFee"
  ): TypedContractMethod<[_baseFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasuries"
  ): TypedContractMethod<
    [_foundationTreasury: AddressLike, _implementerTreasury: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalAnchors"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Anchored"
  ): TypedContractEvent<
    AnchoredEvent.InputTuple,
    AnchoredEvent.OutputTuple,
    AnchoredEvent.OutputObject
  >;
  getEvent(
    key: "AttestationAnchored"
  ): TypedContractEvent<
    AttestationAnchoredEvent.InputTuple,
    AttestationAnchoredEvent.OutputTuple,
    AttestationAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptAnchored"
  ): TypedContractEvent<
    ReceiptAnchoredEvent.InputTuple,
    ReceiptAnchoredEvent.OutputTuple,
    ReceiptAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WarrantAnchored"
  ): TypedContractEvent<
    WarrantAnchoredEvent.InputTuple,
    WarrantAnchoredEvent.OutputTuple,
    WarrantAnchoredEvent.OutputObject
  >;

  filters: {
    "Anchored(bytes32,bytes32,address,bytes32,bytes32,uint8,uint256)": TypedContractEvent<
      AnchoredEvent.InputTuple,
      AnchoredEvent.OutputTuple,
      AnchoredEvent.OutputObject
    >;
    Anchored: TypedContractEvent<
      AnchoredEvent.InputTuple,
      AnchoredEvent.OutputTuple,
      AnchoredEvent.OutputObject
    >;

    "AttestationAnchored(bytes32,bytes32,bytes32,string,string,address,uint256)": TypedContractEvent<
      AttestationAnchoredEvent.InputTuple,
      AttestationAnchoredEvent.OutputTuple,
      AttestationAnchoredEvent.OutputObject
    >;
    AttestationAnchored: TypedContractEvent<
      AttestationAnchoredEvent.InputTuple,
      AttestationAnchoredEvent.OutputTuple,
      AttestationAnchoredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReceiptAnchored(bytes32,bytes32,bytes32,address,address,uint256)": TypedContractEvent<
      ReceiptAnchoredEvent.InputTuple,
      ReceiptAnchoredEvent.OutputTuple,
      ReceiptAnchoredEvent.OutputObject
    >;
    ReceiptAnchored: TypedContractEvent<
      ReceiptAnchoredEvent.InputTuple,
      ReceiptAnchoredEvent.OutputTuple,
      ReceiptAnchoredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WarrantAnchored(bytes32,bytes32,bytes32,string,string,address,uint256)": TypedContractEvent<
      WarrantAnchoredEvent.InputTuple,
      WarrantAnchoredEvent.OutputTuple,
      WarrantAnchoredEvent.OutputObject
    >;
    WarrantAnchored: TypedContractEvent<
      WarrantAnchoredEvent.InputTuple,
      WarrantAnchoredEvent.OutputTuple,
      WarrantAnchoredEvent.OutputObject
    >;
  };
}
